name: email_temporario
description: Projeto de email temporário

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  flutter_widget_from_html: ^0.9.0+2
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#EF3844"
  background_image: "assets/images/icon.png"
  android_12:
    color: "#EF3844"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
